name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: |
          pytest

